%dw 1.0
%output application/java
---
[{
	AIRLINENAME: "PAL",
	CODE1: "PH",
	CODE2: "PHL",
	FROMAIRPORT: "MNL",
	ID: 123,
	PLANETYPE: "Boeing",
	PRICE: 250,
	SEATSAVAILABLE: 22,
	TAKEOFFDATE: |2019-06-20|,
	TOAIRPORT: "SGP",
	TOTALSEATS: 200
}]